### ISSUE TITLE
MGMT: Searching for services via a regex pattern

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#1]
@tsschmidt It seems like in the new material UI version of the app, there is no way to search for service definitions like before. Possibility to restore the behavior and/or make it better?

**Comment by tsschmidt** [comment]
I have just pushed a new branch "mgmt-service-search".  There is a lot going on here in this branch to look at.  
1.  A search box was added to the Header
2.  Search Results screen was added that will appear when the search box issues change event
3.  cas-management.css was removed to hopefully speed up the compile a bit and to reduce static content that needs to be downloading.  The forms rely only on the Material UI Icons and the Font Awesome is no longer used.
4.  The header and the Tab bar for the form are now in a fixed position and the content will scroll underneath then when necessary.

The search is not fully functional yet, you can type anything into it and it returns all services in the manager currently.  Should the search only apply to serviceId or should it apply to text in the name and description as well?

**Comment by mmoayyed** [comment]
Cool. I'll pull it down and try.

My vote is that the search should accept a regex pattern (unknownst to the user) and it should match on the service id, name and description.

**Comment by mmoayyed** [comment]
Pulled. All looks good except that I dont really see a search results window, when I begin typing. (Doesn't matter what I type).

**Comment by mmoayyed** [comment]
also merged with master to resolve a few compile issues.

**Comment by tsschmidt** [comment]
you need to tab out, I have it onChange only for now.  Not sure if we want to search on every keystroke, because it calls an endpoint for results

________________________________

**Comment by tsschmidt** [comment]
Lateest push to the search branch now navigates to search on 'keyup' events.  The search has also been coded to regex match the name, the service id and the description.
________________________________

**Comment by mmoayyed** [comment]
Looks good. Comments:

The back button behaves rather unexpected. It seems to be keeping track of history on the page where each "back" click goes back to the previous state, rather than a "home" type location. For example, if I run 4 different search operations and in the end start clicking the back button, it starts showing me the search results for the 4th attempt, then 3rd, then 2nd, the 1st. Finally, back to "home". Seems odd.

All else works fine.

**Comment by mmoayyed** [comment]
merged master into this branch and pushed.
