### ISSUE TITLE
MGMT: Service Properties should turn into a dropdown?

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#11]
It would be nice if we could collect the list of properties that currently exist, and turn into dropdown for service properties so that one can easily choose what's available.

**Comment by tsschmidt** [comment]
Is there a single place of documentation for all the possible property values?

**Comment by mmoayyed** [comment]
No. Settings are scattered throughout documentation and apply to specific functions.

Here is the list:

```
wsfed.relyingPartyIdentifier
jwtAsResponse
jwtSecretsAreBase64Encoded
jwtEncryptionSecretMethod
jwtEncryptionSecretAlg
jwtSigningSecretAlg
jwtEncryptionSecret
jwtSigningSecret
```

**Comment by tsschmidt** [comment]
An implementation of this has now been pushed.  Take a look and see if it is what you expected.
