### ISSUE TITLE
MGMT: Pairwise subject id generation fields for OIDC type

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#12]
- subjectType: values should be public or pairwise. Default is public, in dropdown mode.
- sectoreIdentifierUri: input field as text

Merge with master once. These two fields deal with pairwise subject id generation for OIDC. 

If a subject type is set to be pairwise, the username attribute provider should also provide a specific option. Similar to anonymous. 
https://github.com/apereo/cas/blob/master/docs/cas-server-documentation/installation/OIDC-Authentication.md#register-clients

**Comment by tsschmidt** [comment]
This has been added
