### ISSUE TITLE
MGMT: Support consent policy for attribute release policy

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#13]
Per discussions, here are the API changes:
https://github.com/apereo/cas/blob/master/docs/cas-server-documentation/integration/Attribute-Release-Consent.md#attribute-selection

```json
{
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
  "serviceId" : "sample",
  "name" : "sample",
  "id" : 100,
  "description" : "sample",
  "attributeReleasePolicy" : {
    "@class" : "org.apereo.cas.services.ReturnAllAttributeReleasePolicy",
    "consentPolicy":
    {
      "@class": "org.apereo.cas.services.consent.DefaultRegisteredServiceConsentPolicy",
      "excludedAttributes":["java.util.LinkedHashSet", ["test"]],
      "includeOnlyAttributes":["java.util.LinkedHashSet", ["test"]],
      "enabled": true
    }
  }
}
```

UI should provide the option so the collection of attributes that are included/excluded can be manipulated on screen. (allow for adds/remove, etc)

**Comment by tsschmidt** [comment]
I have added this in the latest push.  Take a look and see if it was what you were expecting
