### ISSUE TITLE
MGMT: Support surrogate access strategy

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#14]
So per discussions, here's the final outline of the access strategy for surrogate/impersonation:
https://github.com/apereo/cas/blob/master/docs/cas-server-documentation/installation/Surrogate-Authentication.md#surrogate-authorization

Looks very similar to the default, and you need to build support for 3 fields essentially. Two booleans and one Map.

**Comment by tsschmidt** [comment]
I have coded the front end for this, but am not able to save on the server side due to SurrogateRegisteredServiceAccessStrategy not being included in the build.  When I add that project though, I get the config errors on application start up.

**Comment by mmoayyed** [comment]
Good point. Let me take a look. Might need to move it around a bit into more of a core/api type of module. Stand by please.

**Comment by mmoayyed** [comment]
I believe this is fixed in the latest apereo/cas master now. Please merge and the relevant module should be included by default. There may be one or two quirks yet; LMK if you run into issues please.

**Comment by tsschmidt** [comment]
A new issue now:

Caused by: java.lang.NoClassDefFoundError: org/apereo/cas/authentication/AuthenticationCredentialsLocalBinder

**Comment by mmoayyed** [comment]
Ah, that's what I was afraid of. Thanks. I'll have to do some creative maneuvering around this. Hang tight for a bit.

**Comment by mmoayyed** [comment]
Turns out, I may have discovered a bug in the surrogate functionality where the usage of `AuthenticationCredentialsLocalBinder` needs to be rethought. So for the time being, please focus on other tasks and issues and I'll update this once I figure out how to make it work without that component which would not only solve the bug there, but the issue here too.

**Comment by mmoayyed** [comment]
Found a decent solution, with a very minor compromise. I'll have updates by end of day, if not sooner.

**Comment by mmoayyed** [comment]
Pushed the fix upstream. The compromise is, that I had to remove the `surrogateSsoEnabled` flag for the time being. If needed, can be worked out later with better options than the use of the authentication binder. Please give this another try and let me know how it goes.

**Comment by tsschmidt** [comment]
Added
