### ISSUE TITLE
MGMT: Support Owners of a given registered service

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#15]
@tsschmidt Going to try to add the following to the Service API:

`owners`: as a `Map<String, String>` where key is the owner name and the value could be free-form text most commonly some sort of contact info like email, phone, etc. Final result might look like this:

```json
{
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
  "serviceId" : "testId",
  "name" : "testId",
  "id" : 1,
  "owners" : {
      "@class" : "java.util.HashMap",
      "Misagh Moayyed" : "mmoayyed@somewhere.org, 123-456-7890",
      "Person2" : "person2@somewhere.org",
    }
}
```

How close is this to your implementation? We dont need to break apart the contact info into individual fields right? I think that's a bit overkill.

**Comment by mmoayyed** [comment]
I also think we might want to add a `createdBy` field that gets set to the userid of the person creating the record. It would be userid of the person logged into the management UI. This should be an optional field to preserve compatibility, and when things get loaded by core (and even in the UI) we can warn for blankness. 

How does that sound?

**Comment by tsschmidt** [comment]
This is how we modeled it:

contacts:
  [
    java.util.ArrayList
    [
      {
        @class: org.apereo.cas.services.RegisteredServiceContactImpl
        name: Travis S Schmidt
        phone: 530-752-0855
        email: tsschmidt@ucdavis.edu
        department: IET Enterprise Applications and Infrastructure Services
      }
    ]
  ]

I added an endpoint in our version to call and populate a contact to be the person creating the service.

**Comment by mmoayyed** [comment]
Cool, thanks. Lets pause on this until we are done with RC3 and once you're back from vacation. I am trying to figure out if this particular thing in any way can be used or be in relationship with some variation of multi-tenancy. If not, then we'll likely go with your existing solution. 

One thing to note however, is that I don't think created-by necessarily equals a contact. I can call you up and have you create a record for me, but then you would be the author and I'd be the contact. That probably deserves both fields and if no contacts are specified, then we make automatically make them be equal for sanity.

**Comment by mmoayyed** [comment]
Circling back to this; is there a need at this time to keep a separate `createdBy` field? The more I think about it, the more I realize `contacts` as you have should suffice just fine.

**Comment by tsschmidt** [comment]
That works for me.  Do you want me to submit a branch with our contacts implementation?

**Comment by mmoayyed** [comment]
Sure. Please do. I am assuming the branch does not yet include the supporting changes for the mgmt app? If not it would be great if you could add support for contacts all in one spot. I'll work on QA and docs, etc.

**Comment by tsschmidt** [comment]
Not yet, I can add it to the mgmt-enhancements branch or create a separate
one just for the contacts if that is easier for you.

**Comment by mmoayyed** [comment]
Separate would be great! Thanks.

**Comment by tsschmidt** [comment]
Implemented solution has been pushed to mgmt-contacts

**Comment by mmoayyed** [comment]
Posted working PR. Would you want me to merge and fix up the build failures (styling, etc) or would you rather finalize the PR yourself?

**Comment by tsschmidt** [comment]
I thought I fixed all the ones that can be fixed.  Those .ts issues are not really issues.

________________________________

**Comment by mmoayyed** [comment]
Ah, weird business with CI it must be. I'll see what I can do.

**Comment by mmoayyed** [comment]
Closing for now.
