### ISSUE TITLE
MGMT: Add support for SAML2 Service "skip" options

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#18]
https://apereo.github.io/cas/development/installation/Configuring-SAML2-Authentication.html#saml-services

- skipGeneratingAssertionNameId
- skipGeneratingSubjectConfirmationInResponseTo
- skipGeneratingSubjectConfirmationNotOnOrAfter
- skipGeneratingSubjectConfirmationRecipient
- skipGeneratingSubjectConfirmationNotBefore

**Comment by tsschmidt** [comment]
Added
