### ISSUE TITLE
Merge with apereo/cas:master?

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#20]
@tsschmidt I believe we have reached a pretty good milestone with all major issues closed and resolved, huge thanks to you. At this point, would you say this is a good time to do a PR to apereo/cas master and merge so that more folks are given the opportunity to test the baseline functionality while newer shinier things are added, like the domain screen, contacts, etc? Or would you rather wait until at least support for domains is done?

**Comment by tsschmidt** [comment]
I agree now would be a good time to merge.

________________________________

**Comment by tsschmidt** [comment]
I guess one caveat before we merge.  Is everyone on board with the new architecture, Angular/TypeScript/Material UI?  What about the project structure?

**Comment by mmoayyed** [comment]
We have tentatively "lost" a few folks who I'd hoped would be able to review and provide suggestions, if any. While that may still happen, assuming we find the right time and funding, I don't think that should stop us from going forward. So I would personally trust your judgement entirely, and I suppose with time we'll continue to make incremental changes to make things look better.

**Comment by mmoayyed** [comment]
So assuming you're OK with the current standings, shall I proceed to create the PR and then merge? or would you still rather wait until we get a few more eyeballs on this?

**Comment by tsschmidt** [comment]
I feel pretty good about it.  I have only a week in the office before a two week vacation, so I say either do it now, or wait until I am back in case issues arise.

**Comment by mmoayyed** [comment]
Coolio. We'll do it now then. Hopefully by the time you're back we'll only have a few issues to resolve and work through. Thanks!

**Comment by mmoayyed** [comment]
This is done. You're welcome to stick with the same branch or start a new one (new one likely would be easier).

Have a wonderful vacation!
