### ISSUE TITLE
MGMT Issue: Unable to remove SAML Attribute Name Format row

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#21]
- Add a new service, choose type to be SAML2 SP.
- Go to the SAML SP tab, scroll down to the SAML attribute formats table

The title here should say "SAML Attribute **Name** Formats".

- Click the plus sign to add a new row (dont add anything; not sure if that matters)
- Click the trash icon to delete the new row. The row cannot be deleted.

**Comment by mmoayyed** [comment]
Weird. Now I can! Let me try to get the exact sequence down first to duplicate this.

**Comment by mmoayyed** [comment]
Ah, this is how you can duplicate it:

- Edit a service first
- While in edit mode, click "Add a new service".

The repeat the same exercise in the original description by selecting a SAML2 type, etc and then you should see the issue. Doesnt have to be fixed, but it is a bit strange.

**Comment by tsschmidt** [comment]
This came down to a copy/paste error.  I also fixed the formatting and the name of the title.
