### ISSUE TITLE
MGMT: Support addition of arbitrary "required attributes" for access strategy

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#22]
Presently, the "required attributes" section of access strategies is only populated with what the server passes on. It would be great (similar to Properties, etc) if one could add arbitrary attributes as well to not have to list every single attribute in the config apriori. Anything that is saved should be understood by the server of course, regardless of whether or not defined previously.

**Comment by tsschmidt** [comment]
This was changed to match the rejected attributes functionality.
