### ISSUE TITLE
MGMT: Duplicate gradle build for dev vs prod

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#23]
In the interest of speeding of the build for the management webapp, I noticed the command I use is:

```bash
cd webapp-mgmt/cas-management-webapp
gradlew build install bootRun --build-cache --parallel -x test -x javadoc -x check -DenableRemoteDebugging=true --offline --stacktrace
```

In the logs I then see:

```bash
> cas-management-angular-webapp@0.0.0 build /Users/Misagh/Workspace/GitWorkspace/cas-server/webapp-mgmt/cas-management-webapp
> ng build --prod

 10% building modules 3/3 modules 0 active     80% chunk modules optimization     8  95% emitting    Date: 2017-09-07T09:15:28.915Z [1m 21s]src/styles.css
Hash: 3d370c2e9bf1a8e781da
Time: 56404ms
chunk {0} polyfills.571b5ceaa825efdf4d23.bundle.js (polyfills) 57.5 kB {4} [initial] [rendered]
chunk {1} main.6ce7d59b63a846cfd244.bundle.js (main) 619 kB {3} [initial] [rendered]
chunk {2} styles.8fd9182324745c251002.bundle.css (styles) 162 kB {4} [initial] [rendered]
chunk {3} vendor.5f8c9a2aea399e37e870.bundle.js (vendor) 1.19 MB [initial] [rendered]
```

Then it continues with:

```bash
> Task :webapp-mgmt:cas-management-webapp:buildClientDev

> cas-management-angular-webapp@0.0.0 buildDev /Users/Misagh/Workspace/GitWorkspace/cas-server/webapp-mgmt/cas-management-webapp
> ng build

 10% building modules 3/3 modules 0 active  75% advanced module optimization   84% m  95% emitting   Date: 2017-09-07T09:16:03.974Z98% EXECUTING [1m 56s]
Hash: b8f34f90434aba267d0a
Time: 24315ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 472 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 185 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 211 kB {inline} [initial] [rendered]
```

This doesn't seem right/efficient to me. Do we really need to run `ng build` and `ng build --prod` at the same time? Is there a specific set of build commands expected here to avoid this? 

Suggestions:

- bootRun should always run `buildClientDev`. Nothing else.
- If building and releasing snapshots, quite possibly `buildClientDev` too (though this is debateable).
- If building and releasing actual releases, then `buildClient` or if forced from the command line.

**Comment by tsschmidt** [comment]
Yeah it wasn't meant to do both.  Not sure why it is.  Do you usually start work at 3am or are in some other timezone now?

**Comment by tsschmidt** [comment]
Changing the "group" attribute fo the buildClientDev from "build" to "bootRun" solved the issue.  Only --prod is now executed on a build.  Committed to Unicon you can merge to Apereo?

**Comment by mmoayyed** [comment]
Different timezone. Thanks for the fix. Which branch should I use? or same?

**Comment by tsschmidt** [comment]
I committed to the same branch for the fixes and tried to merge all your master changes correctly, hopefully.

________________________________

**Comment by mmoayyed** [comment]
Cool. Thanks.

**Comment by mmoayyed** [comment]
Something is definitely off here because when I try to create a PR, changes show up from back in April, etc. You sure the merge went through correctly?

**Comment by tsschmidt** [comment]
Not 100%, I looked through the conflicts the best I could.

________________________________

**Comment by tsschmidt** [comment]
What files are the April changes in?


________________________________

**Comment by mmoayyed** [comment]
See this link please (April was my bad, had not selected the right branch due to being a dork, but still things look strange):
https://github.com/apereo/cas/compare/master...Unicon:mgmt-angular-json

Do you mind if I attempt to merge master back into your branch once more to see what's up? Might be git weirdness.

**Comment by tsschmidt** [comment]
I think the merge looks a bit weird, because I didn't pull from master before making my changes this morning.  So there was conflicts with the javadoc clean up and other things that you did.  Looking at the changed files though everything looks to be correct to me.


________________________________

**Comment by mmoayyed** [comment]
ok. Lets merge then PR then. Worst case, we review again :)

**Comment by mmoayyed** [comment]
By the way, this still happens. The buildClient task is run and then buildClientDev.

**Comment by tsschmidt** [comment]
Why do you do this?


gradlew build install bootRun


both build and bootRun in the same command?

________________________________

**Comment by mmoayyed** [comment]
Are you suggesting that I should run them separate? or that there is no need to run the triplet of build/install/bootRun? I suspect I can get away with bootRun only. I am not entirely sure why; possibly this may have had to do with earlier boot versions and CAS. May not be needed now of course.

**Comment by tsschmidt** [comment]
I have never tried to bootRun from the command line, so not sure if that
makes a difference.  I have always run it from Idea like this:
[image: pasted2]
Starts up fairly quickly.
