### ISSUE TITLE
MGMT: Thymeleaf templates may be removed?

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#24]
Do we need to keep the thymeleaf templates in src/main/resources/fragments or can they be removed?

**Comment by tsschmidt** [comment]
Removed

**Comment by mmoayyed** [comment]
Follow up question: should the following resources be kept? are they used?

- src/main/resources/templates
- src/main/resources/static (and sub directories such as js, etc)

**Comment by tsschmidt** [comment]
For the moment authorizationFailure.html, error.html, and logout.html are still used.  In fact we need to restore the header and footer fragments we removed in order for the screens to appear correctly.


In static, the js can be removed, all images except the logo can be removed.


css and fonts may need to stay for the static screens to render correctly.

________________________________

**Comment by mmoayyed** [comment]
Thanks. Would you want me to remove them, or could you make the changes as part of an existing branch we have today?

**Comment by tsschmidt** [comment]
Yes, I can get this functioning again today, probably do it in our original branch


________________________________

**Comment by tsschmidt** [comment]
I have pushed to mgmt-angular-json with this functionality restored and the static resources trimmed.

________________________________

**Comment by mmoayyed** [comment]
Merged with apereo/cas master. Lets retire this branch for now altogether. Merges are getting a bit weird :)

**Comment by mmoayyed** [comment]
By the way, build seems to fail on this block:

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

...in the cas-management.css file. Should this also be removed?

**Comment by tsschmidt** [comment]
I crossed myself up on this and the other branches.  So the fonts dir needs to be restored for this branch.  If we merge the domains branch or the search branch then these fonts can be removed from the css.

**Comment by tsschmidt** [comment]
Committed with the fonts restored

**Comment by mmoayyed** [comment]
Excellent. Thanks for the update. I'll wait until we finalize work on those branches, unless you tell me it's good to go. I'll continue to QA things.
