### ISSUE TITLE
MGMT: Default material theme shoud match CAS' own look and feel?

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#27]
I see the following pre-built themes are available:

- deeppurple-amber.css
- indigo-pink.css
- pink-bluegrey.css
- purple-green.css

Could we switch the default theme to something from above that matches the CAS/Apereo theme a bit more closely? I understand most folks are going to rip out the CAS theme anyway, but perhaps by default the two should try to look similar?

**Comment by tsschmidt** [comment]
Changed to deeppurple-amber for now.  At least gets rid of the pink and replaces it with yellow that matches better.  Setting up a custom theme will help others in the future override to their own liking.

**Comment by tsschmidt** [comment]
The mgmt-search service branch now contains a cas-theme.scss that matches the color scheme better.  End users can also copy or change this file to theme the material components to their liking
