### ISSUE TITLE
MGMT: Add user roles and permissions support

### ISSUE THREAD

**Issue by tsschmidt** [Unicon/cas#28]
Add support so that users can be defined as admins or users and also which "domains" a user is allowed to edit.

**Comment by tsschmidt** [comment]
I have pushed a new branch "mgmt-user-roles".  This is the implementation I am currently using to handle this functionality.  Please feel free to rip it to sheds, throw it away completely or modify it.

**Comment by mmoayyed** [comment]
Starting to look into this and review. Updates incoming.

**Comment by mmoayyed** [comment]
Couple of notes, first pass, out loud:

- Like the watcher capability very much. We should definitely port that over.
- How exactly do domain-level permissions work? Are they basically saying "User U has these roles, and when dealing with a particular domain can be these roles?"
- Could you share examples of both your users file and the domain file with some data so I can try to understand the relationship between the two?
- We might want to think about a layer above the authz generator that deals with specific storage options. The authz generator reads things from the storage abstraction and then deals with authz only. This allows us to use many authz generators with many storage types (i.e. properties file might be too limiting, and we might want to switch to JSON with that object that represents everything; probably the better option I'd say)

**Comment by tsschmidt** [comment]
The user-details.properties is used exactly like the default management app uses it.  For our use cases a user can have one of two roles: ROLE_ADMIN or ROLE_USER.  

Admins have complete access to all domains including default and can approve pulls and publish services.  

Users can only view and edit domains they have been given access to through the user-domains.properties.  So entry would like this: 

casuser=notused,www.apero.org,www.jasig.org

And the app would limit them to only seeing these domains on the screen.

Definitely open to using JSON or other storage options as long as it can be added to without restarting the application.  Also a nice feature that we have not coded in the app yet would be the ability to add/remove users permissions to a particular domain.  That would be a nice addition to that menu button on the Domains screen.

**Comment by mmoayyed** [comment]
Is there an opportunity to consolidate down to one file with this?

```
casuser=notused,ROLE_USER,ROLE_APEREO,ROLE_JASIG
```

Specially since for you, your domain definitions are "well formed", this might work better with one less thing to watch? 

I'll see if I can put together a prototype for the storage layer. Most likely next week after RC3 is out. 

Keep up the good work!

**Comment by tsschmidt** [comment]
Domains are actually fluid.  Creating a service with a new domain is enough to create that domain.

**Comment by mmoayyed** [comment]
Makes sense. I had in mind that perhaps auto creating a domain might add a role too, but that's obviously both impractical and a breach :) 

So cool. Also like the ability to assign and configure roles directly in the webapp though I imagine depending on the storage used some of those things possibly come from LDAP or Grouper perhaps once we do the abstraction bit! and the UI bit likely would appear likely via some condition.

Exciting!

**Comment by mmoayyed** [comment]
I have ported over as much as I could from this branch. Some highlights include:

1. The webapp is allowed additional authn options so as to not require the presence of an external CAS server.
2. In addition to properties, we have options now for storing authz rules for user profiles in form of JSON & YAML.
3. All properties, JSON and YAML files are made auto-watchable and auto-reloadable much in the same way everything else in CAS is. 
4. There is a `/user` endpoint that can report back the constructed user profile, along with roles and permissions.

For domains, I believe you'd transformed those into permissions, and you should be able to that easily with the JSON backend.

Docs:
https://apereo.github.io/cas/development/installation/Installing-ServicesMgmt-Webapp.html

Please review when you get a chance and let me know what you think.

**Comment by tsschmidt** [comment]
This all looks good and I think should do what we want.  I will starting using when I integrate our git workflow.

**Comment by mmoayyed** [comment]
Excellent. Closing for now.
