### ISSUE TITLE
log4j2.xml not recognized if externalized

### ISSUE THREAD

**Issue by rkorn86** [Unicon/cas#28]
Branch: mgmt-webapp

`log4j.config.location=file:/etc/cas/management/log4j2.xml` does not seem to work: `ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console`
Using log4j2.xml via `log4j.config.location=classpath:log4j2xml` works. I have the same log4j2 setup (`log4j.config.location=file:/etc/cas/log4j2.xml`) in cas-server-webapp, working perfectly.

**Comment by mmoayyed** [comment]
Thanks for the report. We'll certainly look into this. The changes that exist in CAS may not have been applied to the management webapp. So we'll need to investigate.

Also, if you have the time, all PRs are welcome even if they are tiny :) Post PRs to same branch here on this fork when you find the issue you plan to work on.

**Comment by mmoayyed** [comment]
https://github.com/Unicon/cas/pull/29
