### ISSUE TITLE
MGMT: Issue with regex pattern that calculates domains for service ids

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#31]
It appears that the pattern used to determine domains has changed to `^\^?https?://([^:/]+)`.

This creates the following problem (and breaks tests):

- I'll register a service as such `https://example\\.com/high/.*`.
- Tracking domain is calculated as `example\.com`
- A service request comes in, identified as `https://example.com/high/`.
- CAS tried to calculate domain, comes up with `default`.
- CAS reports back that service is unauthorized and service is not found.

**Comment by mmoayyed** [comment]
perhaps something like to calculate domains:

```
String domain = match.lookingAt() && !match.group(1).contains("*") ? match.group(1) : "default";
domain = StringUtils.remove(domain, "\\");
```

**Comment by tsschmidt** [comment]
I think that would work just fine.  Other possibility is do a replace before matching, but doing it after seems more efficient.  A real solution may be to create a "Domain" object, like we discussed in the meeting this morning.  Then the domain can be added just as a string.  Also defaults for all services in that domain could be set that are copied to any service created.  Could solve some issues, but also cause other issues.

**Comment by mmoayyed** [comment]
Turns out that the fix is simply impractical, because there is a wide [infinite?] range of special characters that we may need to strip out. Consider service patterns that would be like `test?.*[a-z].org` and such where the domain will be calculated as one with special regex characters, yet it could allow many matching "regular" service urls that whose domain would be "test.org" somehow. 

While we likely can make it work by enumerating every possible permutation that would be removed, I find your suggestion much more practical that `Domain` should simply be an arbitrary string, defaulted to "default" and rather than calculating it automatically, we let adopters "group" urls together somehow. In fact, domain probably would a bad choice; "group" or "category" like would be better. 

I'll experiment with this option a bit more; but for the time being in leu of release coming up, I'll reset back to the previous pattern to bypass this issue for now.

**Comment by mmoayyed** [comment]
Initial prototype to keep things simple for the time being:

```java
private String getDomain(final String service) {
        try {
            if (urlValidator.isValid(service)) {
                final URL url = new URL(service);
                if (domainValidator.isValid(url.getHost())) {
                    return url.getHost();
                }
            }
        } catch (final Exception e) {
            LOGGER.trace(e.getMessage(), e);
        }
       // initial value is "default"
        return RegisteredService.INITIAL_DOMAIN_VALUE;
    }

    // Note the new r.getDomain()
    private void addToDomain(final RegisteredService r, final Map<String, TreeSet<RegisteredService>> map) {
        final String domain = StringUtils.defaultIfBlank(r.getDomain(), RegisteredService.INITIAL_DOMAIN_VALUE);
        ....
    }
```

Back to your point and possibly as the next step, it sounds like we are approaching something like "template services or policies", and when I think about it, it also sounds like it's a concept useful in the management app only. For example, an adopter could set up a number of template policies for various services that describe attribute release, theme, etc. Then, when a new service is about to be created, the adopter is given a chance to inherit from a pre-existing policy and leave everything alone, or continue to override settings at the service level. The backend in the end creates the same exact service definition and body; it's just a matter of how it gets populated.

The advantage of keeping as a management app feature is that it keeps the core model clean with less fangs; because in the end the full body of a service object is populated and saved just as it happens today, regardless of how that object was populated. If one changes anything in the service directly, changes are reflected. If one changes anything in the policy that parents a service, then the values are populated all the same and saved for that service. 

The disadvantage might be the duplication of data both in templates in one place, and when each service is populated and saved.  I am ok with that drawback for the consequences are far too severe. The alternative would be too complicated where the core model "everywhere" needs to consult to see if there is a policy and use that or fall back onto its own settings. Assuming the service object already has everything populated via whatever means I think is most practical.

**Comment by mmoayyed** [comment]
Also note that in the above snippet the management app would be responsible for presenting a "domain" field to the user, auto-populating it appropriately perhaps when a serviceId is provided, which means that it can allow for a little bit of intelligence guessing the domain from the pattern while also allowing the user to correct the entry. Which means no more guess work for the core model and the services manager with tiny improvements for performance.

**Comment by tsschmidt** [comment]
In your prototype above, are urlValidator and domainValidator utils that
already exist?  Since domains can only contain letters, numbers and
hyphens, I think we only need to check that these rules are met to know if
it is a single domain or expression representing multiple domains.  The
only issue still is escaping the "\\.".

**Comment by dima767** [comment]
For the "template definition" vs "real service definition", sounds like `Prototype` design pattern.

**Comment by mmoayyed** [comment]
@tsschmidt Yes those utilities already exist. Are you saying that if the domain contains any of those special parameters, we would auto-fallback to the default? and only if single domain, we register the definition under the domain? 
In other words, if "domainValidator.isValid==false then default otherwise use domain"? 

That might work with a few special checks and conditions, but I think it will still be problematic. I'll run some experiments with tests and see if I can get this to fail.

**Comment by tsschmidt** [comment]
So here is my proposed solution.  

```
private final Pattern domainExtractor = RegexUtils.createPattern("^\\^?https?://([^:/]+)");
private final Pattern domainPattern = RegexUtils.createPattern("^[a-z0-9-.]*$");

```
```
    private String getDomain(final String service) {
        final Matcher extractor = domainExtractor.matcher(service.toLowerCase());
        final String domain;
        if (extractor.lookingAt()) {
           final String group1 = StringUtils.remove(extractor.group(1),"\\");
           final Matcher match = domainPattern.matcher(group1);
           domain = match.matches() ? group1 : "default";
        } else {
           domain = "default";
        }
        LOGGER.warn("Domain [{}] found for service [{}] ", domain, service);
        return domain;
    }
```

**Comment by mmoayyed** [comment]
How about something like `http://www.jasig.org.+`? Do we want to handle and calculate the domain there as well? How about `http://www.jasig.org?param=test`?

**Comment by mmoayyed** [comment]
Also the above solution also presents many test failures, specially with `Cas20ResponseViewTests`.

**Comment by tsschmidt** [comment]
So basically we are missing the cases where the expression does not include the slash denoting the start of the path.  In this case it all works well if this is the only service defined  or all services are defined the same way as in your example.  They would be put in the default list and found correctly.  

If a service with id `http://www.jasig.org/somepath/.*` is added, then this entry would cause a www.jasig.org entry to be created in the hashmap and only this list would be traversed and the previous two service ids would not be able to be matched.  

It looks like in order to use the DomainServicesManager correctly, service ids will need to be constructed a certain way.  This constraint was assumed on our part for our use, but may not be reasonable to apply to everyone, especially those with existing registries.  

I see two choices:
  1.  Restore DefaultServicesManager and those wanting to use DomainServicesManager need to configure it to override.
  2. Keep DomainServicesManager as the default.  Add a cas.mgmt.useDomainManager property to the configuration.  If true the then all services are added to the "default" domain and the Domains landing page is not displayed in the webapp.

I am also open to any other suggestions.

**Comment by mmoayyed** [comment]
> It looks like in order to use the DomainServicesManager correctly, service ids will need to be constructed a certain way. 

Yes exactly. This is the same conclusion I arrived at.

> Keep DomainServicesManager as the default. Add a cas.mgmt.useDomainManager property to the configuration. If true the then all services are added to the "default" domain and the Domains landing page is not displayed in the webapp.

I like this option, except that I think we need to do this for the core webapp, because right now tests are failing with "Unauthorized service: not found" errors. So to reformulate your idea:

1. Use DefaultServicesManager as the default
2. Expose an option where when set to true, creates a `DomainServicesManager`. This restores default behavior, and allows you to easily switch for your own purposes.

```java
    @ConditionalOnMissingBean(name = "servicesManager")
    @Bean
    @RefreshScope
    public ServicesManager servicesManager(@Qualifier("serviceRegistryDao") final ServiceRegistryDao serviceRegistryDao) {
        if (blah) then Domain else Default
    }
```
3. The management app could use the same setting, but more practically and easier, perhaps it can do an instanceof check on the servicesManager object it receives and if that is one handling domains, the UI can react appropriately.

**Comment by mmoayyed** [comment]
Quick followup: instanceof may not work due to proxies and  one would add the same setting to the management.properties file anyway to activate it. So nevermind #3.

**Comment by mmoayyed** [comment]
General outline:

```
    /**
     * Determine how services are internally managed, queried, cached and reloaded by CAS.
     * Accepted values are the following:
     * 
     * <ul>
     *     <li>DEFAULT: Keep all services inside a concurrent map.</li>
     *     <li>DOMAIN: Group registered services by their domain having been explicitly defined.</li>
     * </ul>
     */
    private ServiceManagementTypes managementType = ServiceManagementTypes.DEFAULT;
```

Figured ENUM works better to accommodate other implementations of the manager.

**Comment by mmoayyed** [comment]
Via https://github.com/apereo/cas/commit/b74f5fe9402cf209767d54f2dd4ed80bc5e480d8

**Comment by tsschmidt** [comment]
Come on man! You gotta tell me if you are gonna code it.

**Comment by mmoayyed** [comment]
ah, sorry! my bad. I'll definitely be more explicit.

**Comment by tsschmidt** [comment]
No worries.  I will get the mgmt app changes done this afternoon.

________________________________

**Comment by tsschmidt** [comment]
I have pushed "mgmt-domain-regex" that ensures domains only contain valid domain characters.  This branch also has front-end changes that will removes Domains page when the service registry management type is set to DEFAULT

**Comment by mmoayyed** [comment]
Merged.

Quick note: if you would be good to run checkstyle locally once; Things like this will and must be caught:

```java
private String validateDomain(String domain) {
        domain = StringUtils.remove(domain, "\\");
        ...
}
```
