### ISSUE TITLE
MGMT: Sector Identifier URI must be hidden when Subject type = Public

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#32]
For OIDC clients, if subject type is set to public, the sector identifier URI must be hidden. It only applies if the type is pairwise.

![image](https://user-images.githubusercontent.com/1205228/30421957-b389e43a-9953-11e7-806a-10d9c4aee5a0.png)

**Comment by tsschmidt** [comment]
Fix has been pushed to mgmt-domain-regex branch
