### ISSUE TITLE
MGMT: Principal Attribute field should be a dropdown

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#33]
When selecting "Username Attribute" and choosing "Principle Attribute", the field should possibly turn into a dropdown with the current collection of attributes defined:

![image](https://user-images.githubusercontent.com/1205228/30421908-8521ce8c-9953-11e7-92b6-f20deb10d7b5.png)

User must not be limited to attributes in the dropdown; must be able to type anything or select from the list.

**Comment by mmoayyed** [comment]
Same thing needs to be done when "Anonymous" is selected:

![image](https://user-images.githubusercontent.com/1205228/30422129-41cdd3d2-9954-11e7-973e-b433a17f86ed.png)

**Comment by mmoayyed** [comment]
And here:

![image](https://user-images.githubusercontent.com/1205228/30422385-fc195266-9954-11e7-82a1-e635839ffab9.png)

**Comment by tsschmidt** [comment]
Currently the MdAutocomplete widget used to display options and allow user input does not allow multiple selection.  Only one attribute in the list can be selected and selecting an option in the list clears any text that might have been entered.  The fields on the Attribute Release Consent card are both currently coded to be multiple selection.  Anyone wanting multiple attributes will need to type all attributes desired separated by a comma.

**Comment by tsschmidt** [comment]
Fix has been pushed to mgmt-enhancements
