### ISSUE TITLE
MGMT: Multifactor Policy Principal Attribute field should be a dropdown

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#34]
When selecting "Multifactor Policy" the "Principal Attribute name trigger" field should possibly turn into a dropdown with the current collection of attributes defined. User must not be limited to attributes in the dropdown; must be able to type anything or select from the list.

![image](https://user-images.githubusercontent.com/1205228/30422074-0dbffc1e-9954-11e7-9527-18bb07b4dfac.png)

**Comment by tsschmidt** [comment]
Added to the mgmt-enhancements branch

**Comment by mmoayyed** [comment]
Created PR. I will leave it open until we are fully done with that branch. Thanks. Keep pushing and the PR will auto-build.
