### ISSUE TITLE
MGMT: Attribute release policy options are incorrectly shown

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#36]
- Click add a new service 
- Browse to Attribute Release tab

The attribute release policy section only shows 3 policies, and the default selection seems to be "Policy"

![image](https://user-images.githubusercontent.com/1205228/30422512-66806144-9955-11e7-840b-3277fc2c9f7f.png)

Other options are missing that would be: Return Allowed, Return All, Deny, etc
https://apereo.github.io/cas/development/integration/Attribute-Release-Policies.html

Also, for Return All and Return Mapped, etc (just about anywhere where is the possibility to select attributes) the user must have the option type anything or add anything to the list.

**Comment by tsschmidt** [comment]
This was due to some bad logic on adding and remove SAML options from the list when the client type changed.  A fix has been pushed into the mgmt-domain-regex branch
