### ISSUE TITLE
MGMT: Expand Properties pane to avoid text wrapping

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#37]
![image](https://user-images.githubusercontent.com/1205228/30422647-d3dec730-9955-11e7-88bd-735e49d9fcf9.png)

The parent pane, etc could likely be expanded so as to allow the combobox to grow bigger and avoid "...".

**Comment by tsschmidt** [comment]
Looks like the latest material or angular update no longer respected the set width on the md-autocomplete element.  Had to make a css adjustment that has the side effect that all autocomplete popups will have min width of at least 300px.  

Fix pushed to mgmt-enhancements
