### ISSUE TITLE
MGMT: Page footer is missing in all views

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#38]
See below:

![image](https://user-images.githubusercontent.com/1205228/30422733-13d189ea-9956-11e7-9b5b-2c92d64ab7e4.png)

**Comment by tsschmidt** [comment]
Is this really needed?

**Comment by mmoayyed** [comment]
Perhaps not, but if so, the file likely should be removed? I'd leave up to you. Delete probably works best.

**Comment by tsschmidt** [comment]
Any more thoughts on this?  Should it stick to the bottom and content scroll underneath it?

**Comment by tsschmidt** [comment]
I added a smaller, slimmed down fixed footer to the bottom.  pushed in mgmt-5.2-bugs.  I could really take it or leave it.

**Comment by mmoayyed** [comment]
Looks just fine. Merged and closed.
