### ISSUE TITLE
MGMT: Improve UI for service details

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#39]
![image](https://user-images.githubusercontent.com/1205228/30422846-5d50d6ac-9956-11e7-97ca-d3395b7d5158.png)

When a service definition is expanded, the details that show up are very plain-text. This section likely can be improved with better and more attractive UI elements (and more data).

**Comment by tsschmidt** [comment]
A solution has been pushed to mgmt-serviceview-refactor

**Comment by mmoayyed** [comment]
Reviewd. Slightly better. 

I think we ought to "paint" this screen a bit more. I am not quite sure how just yet.

- These: "Release Credential | false, Release Proxy ID | false" simply must go.
- Description seems to already be displayed in the original row that is expanded into details. Do we need to repeat again? 
- I'd recommend that you remove the predefined logo. The logo itself is at odds with how CAS itself calculates logos. The two should match ideally, or simpler would be that you remove the default `cas_logo`.
- It would be good to indicate the service type too?

**Comment by tsschmidt** [comment]
In the existing code the description shown in the list was being limited to a certain length, I don't remember exactly what it was, but I shortened it to 100 characters.  The description being displayed in details is supposed to be the unabridged version.  

The two "Releases", you want them removed completely or changed to be represented by checkboxes?

I only defined the logo in the default services in the project just for testing the display.  I can remove it from those service definitions now.  Were you going somewhere else with this?

Service Type would be good to add too.

A final question is if this functionality is really needed?  Would it be better to just remove it altogether?

**Comment by mmoayyed** [comment]
Cool. 

> A final question is if this functionality is really needed? Would it be better to just remove it altogether?

I think I was headed there too. It's nice to be able to preview the definition at a summary level, but I don't know how practical that might be and I am not quite sure how to make it any better/prettier.

Perhaps it's best to remove it altogether.

**Comment by tsschmidt** [comment]
I have pushed mgmt-remove-details that has this removed if that is the direction we take.  It does clean up a lot of code.

**Comment by mmoayyed** [comment]
Merged. Branch deleted.
