### ISSUE TITLE
MGMT: Error dialog is not rendering correctly

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#40]
- Attempt to delete the HTTPS/IMAPs service
- The error dialog correctly shows up, but it looks like the attached.

![image](https://user-images.githubusercontent.com/1205228/30422975-af814060-9956-11e7-9e73-3f05d8d5a613.png)

**Comment by tsschmidt** [comment]
This fix has been pushed to branch mgmt-domain-regex
