### ISSUE TITLE
MGMT: Editing a service causes it to be duplicated.

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#41]
- Add a new service (doesn't matter what type) and save it.
- Edit the service once added and change its name, description, service id, etc. (it seems to not matter at all if there are any changes. Clicking save would also just do)
- Click save again. The service is duplicated.

**Comment by tsschmidt** [comment]
It seems that objects passed through are always treated as strings no matter how you cast it.  This was an error in the duplicate logic.  The fix has been pushed into the mgmt-domain-regex branch

**Comment by mmoayyed** [comment]
Thanks. Going to merge the branch and then cut Rc3.
