### ISSUE TITLE
MGMT: Access Strategy type Remote should present list of acceptable HTTP codes

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#43]
![image](https://user-images.githubusercontent.com/1205228/30423220-7702a30e-9957-11e7-9908-4660da67d0b9.png)

The field should turn into a list, that would contain acceptable HTTP codes. List is documented here:
https://www.wikiwand.com/en/List_of_HTTP_status_codes

We don't have to list every single code; some of the more commons ones are good such as `200, 401, 500, 404, 403`, etc and must give the user options to type arbitrary codes too (i.e. 854).

**Comment by tsschmidt** [comment]
Added to mgmt-enhancements

**Comment by mmoayyed** [comment]
Excellent. Do you have other changes you wish to push into `mgmt-enhancements`? shall we keep the branch/PR alive for the time being?

**Comment by tsschmidt** [comment]
Yes, keep it alive for now.  What did you want to do with the dropdowns on Attribute Release Consent?  Do we need to find a way to allow multiple selection and free form input?

________________________________

**Comment by mmoayyed** [comment]
Cool.

I am assuming you're referring to:

> The fields on the Attribute Release Consent card are both currently coded to be multiple selection. Anyone wanting multiple attributes will need to type all attributes desired separated by a comma.

In other words:

- I can either select multiple attributes by clicking through
- Or I can begin to type "x,y,z" and have them be selected though this option clears any prior selections

If so, I think that's perfectly OK. There should be a limit to our niceness :)

**Comment by tsschmidt** [comment]
The issue is that we can't have multiple selection by clicking options or the option of typing an option not in the list.  The Autocomplete widget does not have multiple selection as a functionality.

________________________________

**Comment by mmoayyed** [comment]
OK. In that case, let's have the user only pick options from the list removing the ability to type attributes. I think that's the safest path to avoid typos and such.
