### ISSUE TITLE
MGMT: Support expiration policies for service definitions

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#45]
Per earlier conversations, this task is about allowing a service definition to auto-expire (and be deleted) from the registry. 

Things to consider:

1. Should expiration policies be designed as an object of `RegisteredServiceExpirationPolicy` with varying implementations, or should we simply stick to a date field? 
2. Should expired services be deleted automatically, or should they be marked as disabled? 
3. Notifications (email, sms) to send out to contacts if a service is about to expire within a configurable window?
4. Notifications (email, sms) to send out to contacts if a service is deleted/disabled? 

My take is as follows:

1. `RegisteredServiceExpirationPolicy` probably is the better choice.
2. Be deleted, as part of the default policy implementation. Alternative policies may decide to do otherwise.
3. Yes. The "warning window" may be defined as part of the policy implementation
4. Yes.

**Comment by mmoayyed** [comment]
Reflecting on this a bit more, I arrived at something like this:

```json
{
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
  "serviceId" : "^https://.+",
  "name" : "sample service",
  "id" : 100,
  "expirationPolicy": {
    "@class": "org.apereo.cas.services.DefaultRegisteredServiceExpirationPolicy",
    "deleteWhenExpired": true,
    "notifyWhenDeleted": false,
    "expirationDate": "2017-10-05"
  }
}
```

Notable differences from the original take:

> Notifications (email, sms) to send out to contacts if a service is about to expire within a configurable window?

Ignored for now. Shall iterate later.

**Comment by mmoayyed** [comment]
Couple of high-level comments:

- Bit of a risky business, but I think I have managed to move the common functionality of ServicesManager implementations into a base class. This was need to ensure all implementation can process/delete/etc expired definitions, and share as much code as possible. All tests should pass. 
- Likewise, tests are consolidated to share as much as possible when dealing with ServicesManager.
- The `"expirationDate": "2017-10-05"` above is set to also handle `LocalDateTime` to allow for exactness as much as possible.
- On each retrieval operation of the ServicesManager, the resulting service is evaluated for expiry and then processed based on the policy if needed.
- Obviously, all policies (similar to contacts) are entirely optional as far as their presence goes in the definition. 
- In order to avoid stale service definitions that are never retrieved the load() operation of the manager that also runs as a cron job is set to filter and process expired definitions, if any is found.
- Notifications are handled via internal Spring events, rather than something "hardwired" into the ServicesManager. There is a listener that is on the lookout for `CasRegisteredServiceExpiredEvent` that is broadcasted when a service is expired and notifications are needed. The listener handles the submission of notifications in form of sms and email (assuming config is done to enable sms and email providers).
- The properties of the service registry `cas.serviceRegistry.xyz` are extended to include settings for mail and sms that affect things like from/to/subject/cc/bcc, etc.

Still testing. Nothing is public yet, but if needed we can surely do a code review session to find weirdness and improve.

**Comment by tsschmidt** [comment]
> Bit of a risky business, but I think I have managed to move the common functionality of ServicesManager implementations into a base class. This was need to ensure all implementation can process/delete/etc expired definitions, and share as much code as possible. All tests should pass.

I was looking into doing this as well, or have DomainServicesManger extend DefaultServicesManger since so much of the code is exactly the same.  Another approach would be to pass a flag to DomainServicesManager that would only use the "default" domain and it should function the same as the current DefaultServicesManager.

> On each retrieval operation of the ServicesManager, the resulting service is evaluated for expiry and then processed based on the policy if needed.

>In order to avoid stale service definitions that are never retrieved the load() operation of the manager that also runs as a cron job is set to filter and process expired definitions, if any is found.

Having both seems a bit redundant to me.  Since expiration is set to a date only, the number of expired services will only change after 12:00am local time.  I think checking for expired services only needs to happen during on load() for a possible change, and a cron job that runs a 12:01am everyday.  

Looking forward to seeing it.

**Comment by mmoayyed** [comment]
>  Since expiration is set to a date only, the number of expired services will only change after 12:00am local time.

Not quite. The expiration field supports both dates as well as both date/times. IOW there is `LocalDate` and there is `LocalDateTime`. We could pick one, but I thinking keeping hours and minutes, etc would offer a better degree of exactness at no or very low cost. This means that if you set a service to expire on Oct 4 8am and the cron job ran on 7am, you'd have to wait about a day for an expired service to remove. Avoiding this would require one to invent a time machine and carefully tune the schedule, involving the adopter in knowing about much unnecessary detail :)

Still working on tests. I'll post back when things are near ready with docs, etc.

**Comment by mmoayyed** [comment]
This has landed in master.

Initial docs:
https://apereo.github.io/cas/development/installation/Configuring-Service-Expiration-Policy.html

Supporting JSON to represent MGMT app support:

```
{
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
  "serviceId" : "^https://.+",
  "name" : "sample service",
  "id" : 100,
  "expirationPolicy": {
    "@class": "org.apereo.cas.services.DefaultRegisteredServiceExpirationPolicy",
    "deleteWhenExpired": true,
    "notifyWhenDeleted": false,
    "expirationDate": "2017-10-05"
  }
}
```

**Comment by tsschmidt** [comment]
I have pushed mgmt-expiration branch up to unicon with a new tab to set this information.

Ran into some issues:

1.  Datepicker currently only supports picking dates and Timestamps are not yet part of its functionality.  That is why the field is text input only
2. If the date entered is not a format that will parse in LocalDateTime the back end seems to go into a loop.
3.  If a date before now is entered the backend seems to loop and not return correctly.

Some of this I can probably take of in the app, but users can edit the field by other means as well.

**Comment by mmoayyed** [comment]
Yikes. Let me understand this: is the DatePicker something CAS uses as a separate library? or it's part of the angular stack? If it's the former, could we remove and replace with something offered by the framework? I find it odd that a framework offering a date-picker gadget does not support times :)

**Comment by tsschmidt** [comment]
It is part of the Angular Material UI framework.  https://material.angular.io/components/datepicker/overview

It is slated to be added, just has not made it in there just yet.  Datepicker was added not that long ago.

**Comment by mmoayyed** [comment]
Got it. I think what ships is acceptable. Once support for time is added, we'll extend the same feature and those who use the mgmt app can do one of 3 things: wait, stick with dates for now and build support for time :) 

TLGM.

**Comment by tsschmidt** [comment]
Do you want to leave it as an open text input or switch it back to a datepicker widget?  The default MatNativeDateModule returns dates in this format "2017-10-12T07:00:00.000Z".  This blows up the AbstractServicesManager when it tries to parse it with LocalDatetime, and puts the server into an infinite loop.  We are able to override the date module provider with our own implementations and formats, but I will need to figure that out.

**Comment by mmoayyed** [comment]
Two suggestions:

1. Open text input is fine; if would be good if we could a placeholder tag that would show the accepted syntax for dates and times.
2. Sounds like the returned format is one of ZonedDateTime right? This `AbstractServicesManager` should be able to accept that as well.

**Comment by mmoayyed** [comment]
Made sure `AbstractServicesManager` is able to support `ZonedDateTime` (i.e ` "2017-10-12T07:00:00.000Z"`). Merged. Will continue to test.
