### ISSUE TITLE
MGMT: Service URL label should change based on service type

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#46]
The `Service URL` label seems to never change; for better clarity I propose that this text should change based on the service type. For instance, when OIDC/OAUTH, it would be "Redirect URL". If SAML, it would be "Entity ID", etc.

**Comment by tsschmidt** [comment]
Pushed changes to mgmt-tooltip

**Comment by mmoayyed** [comment]
Does the branch account for SAML=Entity ID and WSFED=Consumer URL? I only see the label changing if it's OAUTH/OIDC?

**Comment by mmoayyed** [comment]
Ping.

**Comment by tsschmidt** [comment]
SAML should change to Entity ID, I was not sure if WS Fed changed, so I can get that added.

________________________________

**Comment by tsschmidt** [comment]
This is changed and pushed to mgmt-tooltip branch

________________________________

**Comment by mmoayyed** [comment]
Excellent. Merged. Deleted branch.
