### ISSUE TITLE
MGMT: Contacts should be "tabbed" by name?

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#48]
While this is perfectly good as is, I am wondering if it might be more useful if each contact that is tabbed as 1, 2, 3 should be instead displayed by contact name. That would allow me to very quickly see who the contacts are, and I wouldn't have to step through 2-3 clicks to find Jane Doe.

**Comment by tsschmidt** [comment]
Change has been pushed to mgmt-contacts.  Default tab label is index number until a name is entered.  Also Name and EMail have been set to be Required

**Comment by mmoayyed** [comment]
Looks great. Merged. Branch deleted.
