### ISSUE TITLE
MGMT: Support SAML Credential Type

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#51]
https://github.com/apereo/cas/blob/master/docs/cas-server-documentation/installation/Configuring-SAML2-Authentication.md

`signingCredentialType`: Acceptable fixed values are BASIC and X509. This setting controls the type of the signature block produced in the final SAML response for this application.

**Comment by tsschmidt** [comment]
SAML Client screen is getting somewhat crowded.  Should we look at grouping some of these fields together in their own card and heading?

**Comment by tsschmidt** [comment]
Pushed this to mgmt-saml-credential branch.

**Comment by mmoayyed** [comment]
Sounds good. I can deduce the following groups:

- All the "skipXYZ" fields could potentially go into their own group. Something like "Optional Fields"
- "signAssertions", "signResponses" and "encryptAssertions" probably under a new group "Security"
- All "metadataXYZ" probably under a new group "Metadata"
- nameIdQualifier, serviceProviderNameIdQualifier and requiredNameIdFormat in a new group "Name ID"

As far as SAML goes, I am almost sure we'll be adding new fields and groups :)

**Comment by tsschmidt** [comment]
Pushed the grouping change up to mgmt-saml-credential.  Let me if things need to be moved around or renamed.

**Comment by mmoayyed** [comment]
Looks great. Merged.
