### ISSUE TITLE
MGMT: "Case Insensitive" checkbox in Access Strategy should be moved to "Required Attributes" card

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#58]
The placement of the checkbox makes more sense, when moved to the relevant card it deals with.

![image](https://user-images.githubusercontent.com/1205228/31486680-1c7375fe-af45-11e7-804e-8acc16346a24.png)

**Comment by tsschmidt** [comment]
This has been pushed as mgmt-case-sensitive

**Comment by mmoayyed** [comment]
Merged.
