### ISSUE TITLE
MGMT: Support for Groovy Attribute Release for SAML2

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#59]
Working on a deployment that required me to add this:
https://apereo.github.io/cas/development/installation/Configuring-SAML2-Authentication.html

Identical to other Groovy options(except the script has access to more SAML-related things).

**Comment by tsschmidt** [comment]
Pushed changes to mgmt-saml-groovy.  Take a look, and let me know if anything needs to be done to filter the policy list for different service types.

**Comment by mmoayyed** [comment]
Looks great. merged. deleted branch.
