### ISSUE TITLE
MGMT: Support for REST Attribute Release for Apps

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#60]
New deployment; New attribute release option based on REST endpoint:
https://apereo.github.io/cas/development/integration/Attribute-Release-Policies.html#rest

**Comment by tsschmidt** [comment]
This change has been pushed to mgmt-restful-policy

**Comment by mmoayyed** [comment]
Excellent. Could you merge with apereo/cas:master once please? There a few conflicts that I think you would know best to resolve before merging.

**Comment by tsschmidt** [comment]
Ok, merged and pushed.  I probably should have done these two changes in one branch since they were coded in the same place.

**Comment by mmoayyed** [comment]
This is done and merged.
