### ISSUE TITLE
MGMT: Theme options based on Groovy/REST

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#61]
New options for themes.

Groovy:
https://apereo.github.io/cas/development/installation/User-Interface-Customization-Themes.html#groovy-themes

REST:
https://apereo.github.io/cas/development/installation/User-Interface-Customization-Themes.html#restful-themes

**Comment by tsschmidt** [comment]
Pushed a change to mgmt-theme.  Only thing I changed was the tooltip to tell the user the acceptable type of values.  Were you looking for something more?

**Comment by mmoayyed** [comment]
Nope. That's good enough. We could break this down by explicit types and dedicated fields, etc but we can do all of that later when asked and if needed.

**Comment by mmoayyed** [comment]
Merged. Deleted branch.
