### ISSUE TITLE
MGMT: Retrieve list of supported service properties from server

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#62]
I noticed that we now have:

```typescript
options: PropertyOption[] = [
    new PropertyOption('wsfed.relyingPartyIdentifier','WS-Fed Relying Party Identifier','custom-identifier'),
    new PropertyOption('jwtAsResponse','JWT As Response','true'),
    new PropertyOption('jwtSecretsAreBase64Encoded','JWT Secrets Base 64 Encoded','false'),
    new PropertyOption('jwtEncryptionSecretMethod','JWT Encryption Secret Method','A192CBC-HS384'),
    new PropertyOption('jwtEncryptionSecretAlg','JWT Encryption Secret Alg','dir'),
    new PropertyOption('jwtSigningSecretAlg','JWT Signing Secret Alg', 'HS256'),
    new PropertyOption('jwtSigningSecret','JWT Signing Secret','<SECRET>'),
    new PropertyOption('jwtEncryptionSecret','JWT Encryption Secret','<SECRET>')
  ];
```

Given the list of props are continue to grow and each individual prop may be removed, refactored or even renamed, it would be better if there was some kind of an endpoint to retrieve the list of supported properties. Perhaps `FormData` needs to be extended to include the supported list and the UI would then use that instead of hardcoding/duplicating props. 

I'm working on a deployment that is going to extend `jwtAsResponse` and make it fancier with a few additional props and I would like to reduce the maintenance work on the UI side as much as possible.

**Comment by tsschmidt** [comment]
Sounds good.

**Comment by mmoayyed** [comment]
Sweet. I'll move the collection of settings into an API that can be accessed via the management webapp and keep all in one place. I'll post back when it's done.

**Comment by mmoayyed** [comment]
Please pull from apereo/cas:master once. There is now an enum `RegisteredServiceProperties` in `RegisteredServiceProperty` that lists all supported settings. This is available at the API level and you can use it as `RegisteredServiceProperty.RegisteredServiceProperties.values()` or some such in the management backend to automate the addition of new properties.

Note that I deprecated one property, and added two more. (You don't need to filter the deprecated one). List all for now.

**Comment by tsschmidt** [comment]
Take a look at what I have pushed into mgmt-properties.  This is a WIP.  I need to refactor some of your code to get what I think we wanted.

**Comment by mmoayyed** [comment]
Cool. I'll turn this into a PR so I can review/compare changes easily. Ping when ready.

And thanks very much, as always!

**Comment by tsschmidt** [comment]
I went all out on this refactored all of the hard coded options out of the client code and made them part of the /formData end point.  This should make keeping the client up to date much easier.  I think everything is coded, just need to clean it up and document before pushing again.

**Comment by tsschmidt** [comment]
Finished this up and pushed to mgmt-properties.  Take a look and let me know if we need to change anything.

**Comment by mmoayyed** [comment]
Had a look. 

The collection of enums that are now added to API classes are not going to work because they actually increase maintenance in ways that are forcibly very much manual and somewhat hidden. It seems like all new enums are more or less related to the management webapp functionality and as such don't belong in API classes necessarily, but more importantly, their design defeats the purpose of automation and polymorphism. For instance, if I add a new `RegisteredService` type, or if a new algorithm is added for signing/encryption or if a new MFA provider is added, one would then need to manually update all relevant enums and worse, one would need to *remember* to manually update enums. The fact that I have just added a provider or a new algorithm is not enough on its own and contributors are required to be mindful of extraneous places in the code to indicate the addition of a new type. It's very easy to forget these because there is nothing in the code or automated check to ensure such changes are comprehensive. 

The same logic does not apply to the collection of properties defined because that enum/collection *is* the reference for all supports properties. Then only place you need to touch to introduce a new official property is that enum. 

I understand the intention behind the change; I think this sort of thing is the perfect example of automating the behavior of management webapp based on what is supported in the running server. We'd need some kind of a discovery endpoint that would outline essentially two categories of metadata:

1. Things that are supported in general/theory.
2. Things that are actively configured and running.

Such that by querying this endpoint you could see:

1. What are set of services supported by this CAS server?
2. What set of services *could be* supported by this CAS server?

So on and so forth....and surely, this would remove the need for static hard coding of types and their relevance.

Also, certain bits that are included in these enums are not relevant for an enum. For example, if I call upon a Provider for MFA, that instance should immediately tell me its (friendly) name right there. I shouldn't have to check some outside enum to see what the name is, or any other relevant bits and pieces. Many of these settings could simply be reformatted to have them benefit from basic polymorphic behavior.

For the time being, I suggest you refactor the change with the following:

- Remove all enums from API classes and move them over the management app.
- Place/design them in the management app such that they can, later on, be removed easily and replaced with the contents of the profile endpoint when you query the server. 

I'll continue to work on the discovery endpoint; I am not sure we'd be able to let the change go into 5.2, but perhaps some small foundational work to expose data would be good as a starting point for now and I'll focus on that piece for the time being.

**Comment by mmoayyed** [comment]
Here's a quick mock-up of the change, as WIP:

![image](https://user-images.githubusercontent.com/1205228/32165529-5573d434-bd78-11e7-84bf-553dedc216e3.png)

**Comment by tsschmidt** [comment]
All good points.  I have removed the enums that I added to the APIs.  I am
still using the ones that were already there to populate FormData.  I have
coded the other options not found else where in the code directly into the
FormData.  We can re-hash this later when the endpoint is coded.

Travis

**Comment by mmoayyed** [comment]
Excellent. Merged.
