### ISSUE TITLE
MGMT: OIDC Scopes vs Attribute Release Policy

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#68]
When OIDC is selected as the service type, the attribute release policy is controlled and constructed by the definition of scopes and such. This means we should do one of the following:

- Hide the Attribute Release Policy tab altogether.
or
- Move the scopes and related fields/components to that tab.

The 2nd option probably makes more sense.

**Comment by tsschmidt** [comment]
Would all of these move to the attribute release screen?

![image](https://user-images.githubusercontent.com/19735741/32199465-da3972ee-bd89-11e7-9391-f6083959776b.png)

**Comment by mmoayyed** [comment]
I would guess no. I'd say scopes only deal with attributes and claims and that's probably a sufficient starting point.

**Comment by tsschmidt** [comment]
This change is pushed in to mgmt-5.2-bugs
