### ISSUE TITLE
MGMT: Change attribute release policy options per client type

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#9]
Per my tests, it doesnt seem like some of the new attribute release policy options are taken into account.

When choosing SAML: We have two additional extra policies that deal with R&S and pattern matching.

When choosing WSFED: The only relevant available option should be that of WSFED
https://apereo.github.io/cas/development/protocol/WS-Federation-Protocol.html#claims

Same thing for OIDC; only the OIDC relevant policy should be available (which is built from scopes I believe) All others should go away?

**Comment by tsschmidt** [comment]
Ran into some problems trying to get the SAML InCommon and Matching to be saved in the backend.  Those policies are currently not in the build for the management app and it looks like cas-server-support-saml-idp where they reside can be included into the build.  

It also looks like more then a just a simple refactor to move those files so I am reaching to get some help on that.

**Comment by mmoayyed** [comment]
I believe this is fixed in the apereo master branch. Give it a try with a merge and see if you still run into issues.

**Comment by tsschmidt** [comment]
Fixed with latest push
